import type { Company, ResearchRow, SalarySubmission } from "./types";

export const companies: Company[] = [
  {
    id: "c1",
    name: "Google",
    slug: "google",
    market: "Hybrid",
    headquarters: "Mountain View, US",
    description:
      "Large engineering organization with mature ladders, location-adjusted pay, and deep stock-heavy senior compensation.",
  },
  {
    id: "c2",
    name: "Microsoft",
    slug: "microsoft",
    market: "Hybrid",
    headquarters: "Redmond, US",
    description:
      "Level-driven compensation with broad role coverage across engineering, product, data, and cloud infrastructure teams.",
  },
  {
    id: "c3",
    name: "Amazon",
    slug: "amazon",
    market: "Global",
    headquarters: "Seattle, US",
    description:
      "Highly structured levels with meaningful stock variance and strong compensation spread by location and business unit.",
  },
  {
    id: "c4",
    name: "Atlassian",
    slug: "atlassian",
    market: "Global",
    headquarters: "Sydney, AU",
    description:
      "Distributed product company with clear seniority bands and competitive global remote compensation packages.",
  },
  {
    id: "c5",
    name: "Flipkart",
    slug: "flipkart",
    market: "India",
    headquarters: "Bengaluru, IN",
    description:
      "India-first technology company with level-led engineering compensation and strong senior IC differentiation.",
  },
  {
    id: "c6",
    name: "Razorpay",
    slug: "razorpay",
    market: "India",
    headquarters: "Bengaluru, IN",
    description:
      "Fintech product company where cash-heavy offers and rapid seniority growth make level normalization important.",
  },
];

export const salarySubmissions: SalarySubmission[] = [
  {
    id: "s1",
    companyId: "c1",
    company: "Google",
    companySlug: "google",
    role: "Software Engineer",
    level: "L4",
    levelRank: 4,
    location: "Seattle, US",
    market: "Global",
    currency: "USD",
    base: 178000,
    bonus: 27000,
    stock: 88000,
    totalComp: 293000,
    totalCompUsd: 293000,
    yearsExperience: 5,
    submittedAt: "2026-05-12",
    verified: true,
  },
  {
    id: "s2",
    companyId: "c1",
    company: "Google",
    companySlug: "google",
    role: "Software Engineer",
    level: "L5",
    levelRank: 5,
    location: "Bay Area, US",
    market: "Global",
    currency: "USD",
    base: 214000,
    bonus: 36000,
    stock: 164000,
    totalComp: 414000,
    totalCompUsd: 414000,
    yearsExperience: 8,
    submittedAt: "2026-04-20",
    verified: true,
  },
  {
    id: "s3",
    companyId: "c1",
    company: "Google",
    companySlug: "google",
    role: "Data Scientist",
    level: "L4",
    levelRank: 4,
    location: "Bengaluru, IN",
    market: "India",
    currency: "INR",
    base: 6800000,
    bonus: 900000,
    stock: 2400000,
    totalComp: 10100000,
    totalCompUsd: 121200,
    yearsExperience: 5,
    submittedAt: "2026-03-18",
    verified: true,
  },
  {
    id: "s4",
    companyId: "c2",
    company: "Microsoft",
    companySlug: "microsoft",
    role: "Software Engineer",
    level: "62",
    levelRank: 4,
    location: "Hyderabad, IN",
    market: "India",
    currency: "INR",
    base: 5200000,
    bonus: 800000,
    stock: 1800000,
    totalComp: 7800000,
    totalCompUsd: 93600,
    yearsExperience: 4,
    submittedAt: "2026-05-05",
    verified: true,
  },
  {
    id: "s5",
    companyId: "c2",
    company: "Microsoft",
    companySlug: "microsoft",
    role: "Product Manager",
    level: "64",
    levelRank: 5,
    location: "Redmond, US",
    market: "Global",
    currency: "USD",
    base: 188000,
    bonus: 32000,
    stock: 92000,
    totalComp: 312000,
    totalCompUsd: 312000,
    yearsExperience: 7,
    submittedAt: "2026-04-02",
    verified: true,
  },
  {
    id: "s6",
    companyId: "c2",
    company: "Microsoft",
    companySlug: "microsoft",
    role: "Data Engineer",
    level: "63",
    levelRank: 4,
    location: "Dublin, IE",
    market: "Global",
    currency: "USD",
    base: 146000,
    bonus: 21000,
    stock: 61000,
    totalComp: 228000,
    totalCompUsd: 228000,
    yearsExperience: 6,
    submittedAt: "2026-02-28",
    verified: false,
  },
  {
    id: "s7",
    companyId: "c3",
    company: "Amazon",
    companySlug: "amazon",
    role: "Software Engineer",
    level: "L5",
    levelRank: 5,
    location: "Seattle, US",
    market: "Global",
    currency: "USD",
    base: 176000,
    bonus: 18000,
    stock: 118000,
    totalComp: 312000,
    totalCompUsd: 312000,
    yearsExperience: 6,
    submittedAt: "2026-05-21",
    verified: true,
  },
  {
    id: "s8",
    companyId: "c3",
    company: "Amazon",
    companySlug: "amazon",
    role: "Solutions Architect",
    level: "L6",
    levelRank: 6,
    location: "Austin, US",
    market: "Global",
    currency: "USD",
    base: 198000,
    bonus: 24000,
    stock: 162000,
    totalComp: 384000,
    totalCompUsd: 384000,
    yearsExperience: 9,
    submittedAt: "2026-01-12",
    verified: true,
  },
  {
    id: "s9",
    companyId: "c4",
    company: "Atlassian",
    companySlug: "atlassian",
    role: "Software Engineer",
    level: "P4",
    levelRank: 4,
    location: "Remote, US",
    market: "Global",
    currency: "USD",
    base: 172000,
    bonus: 16000,
    stock: 76000,
    totalComp: 264000,
    totalCompUsd: 264000,
    yearsExperience: 5,
    submittedAt: "2026-05-01",
    verified: true,
  },
  {
    id: "s10",
    companyId: "c4",
    company: "Atlassian",
    companySlug: "atlassian",
    role: "Product Designer",
    level: "P5",
    levelRank: 5,
    location: "Sydney, AU",
    market: "Global",
    currency: "USD",
    base: 151000,
    bonus: 14000,
    stock: 83000,
    totalComp: 248000,
    totalCompUsd: 248000,
    yearsExperience: 8,
    submittedAt: "2026-03-09",
    verified: false,
  },
  {
    id: "s11",
    companyId: "c5",
    company: "Flipkart",
    companySlug: "flipkart",
    role: "Software Engineer",
    level: "SDE-2",
    levelRank: 4,
    location: "Bengaluru, IN",
    market: "India",
    currency: "INR",
    base: 4200000,
    bonus: 700000,
    stock: 1200000,
    totalComp: 6100000,
    totalCompUsd: 73200,
    yearsExperience: 4,
    submittedAt: "2026-04-16",
    verified: true,
  },
  {
    id: "s12",
    companyId: "c5",
    company: "Flipkart",
    companySlug: "flipkart",
    role: "Engineering Manager",
    level: "EM-1",
    levelRank: 6,
    location: "Bengaluru, IN",
    market: "India",
    currency: "INR",
    base: 7200000,
    bonus: 1400000,
    stock: 3100000,
    totalComp: 11700000,
    totalCompUsd: 140400,
    yearsExperience: 10,
    submittedAt: "2026-02-11",
    verified: true,
  },
  {
    id: "s13",
    companyId: "c6",
    company: "Razorpay",
    companySlug: "razorpay",
    role: "Software Engineer",
    level: "SDE-2",
    levelRank: 4,
    location: "Bengaluru, IN",
    market: "India",
    currency: "INR",
    base: 3600000,
    bonus: 600000,
    stock: 900000,
    totalComp: 5100000,
    totalCompUsd: 61200,
    yearsExperience: 4,
    submittedAt: "2026-05-18",
    verified: true,
  },
  {
    id: "s14",
    companyId: "c6",
    company: "Razorpay",
    companySlug: "razorpay",
    role: "Product Manager",
    level: "PM-2",
    levelRank: 4,
    location: "Mumbai, IN",
    market: "India",
    currency: "INR",
    base: 3900000,
    bonus: 900000,
    stock: 800000,
    totalComp: 5600000,
    totalCompUsd: 67200,
    yearsExperience: 5,
    submittedAt: "2026-03-26",
    verified: false,
  },
];

export const researchRows: ResearchRow[] = [
  {
    feature: "Level-first compensation",
    levelsFyi: "Core organizing model",
    sixfigr: "Partial seniority view",
    ambitionBox: "Title and company led",
    glassdoor: "Title led",
    build: "Yes: primary comparison axis",
  },
  {
    feature: "Compensation breakdown",
    levelsFyi: "Base, bonus, stock",
    sixfigr: "Salary ranges",
    ambitionBox: "Salary and benefits",
    glassdoor: "Salary ranges",
    build: "Yes: base, bonus, stock, total",
  },
  {
    feature: "Company pages",
    levelsFyi: "Deep company bands",
    sixfigr: "Company salary pages",
    ambitionBox: "Reviews plus salary",
    glassdoor: "Reviews plus salary",
    build: "Yes: concise company intelligence",
  },
  {
    feature: "India + global comparison",
    levelsFyi: "Strong global tech",
    sixfigr: "India-friendly",
    ambitionBox: "India-centric",
    glassdoor: "Global but broad",
    build: "Yes: normalized USD plus original currency",
  },
  {
    feature: "Submission reliability",
    levelsFyi: "Community reported",
    sixfigr: "Aggregated estimates",
    ambitionBox: "Employee reported",
    glassdoor: "Employee reported",
    build: "Yes: validation and duplicate checks",
  },
  {
    feature: "Decision workflow",
    levelsFyi: "Compare tables",
    sixfigr: "Benchmarks",
    ambitionBox: "Research browsing",
    glassdoor: "Research browsing",
    build: "Yes: 2-3 profile compare",
  },
];
